-- ... (Previous content kept, appending new content)

-- 3. TOURS TABLE
create table public.tours (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  price_text text not null, -- e.g. "From $20 / person"
  image_url text not null,
  category text -- 'safari', 'lake', 'hiking'
);

-- Enable Security
alter table public.tours enable row level security;

-- Policy 1: Public can view tours
create policy "Public can view tours"
on public.tours for select
using (true);

-- Policy 2: Admins can modify tours
create policy "Admins can modify tours"
on public.tours for all
using (auth.role() = 'authenticated');

-- SEED DATA (Only run this once)
INSERT INTO public.tours (title, description, price_text, image_url, category) VALUES
('Lake Bunyonyi Boat Cruise', 'A relaxing motorized canoe trip visiting the history-rich islands.', 'From $20 / person', 'https://images.unsplash.com/photo-1544234057-0df75a74e5cb?auto=format&fit=crop&w=600', 'lake'),
('Gorilla Trekking', 'Track the majestic mountain gorillas in Bwindi Impenetrable Forest.', 'Permit + Guide Fees', 'https://images.unsplash.com/photo-1582234031123-5e927c8d9e72?auto=format&fit=crop&w=600', 'safari'),
('Dugout Canoeing', 'Paddle yourself or be paddled in a traditional tree-trunk canoe.', 'From $15 / person', 'https://images.unsplash.com/photo-1548268770-4384dcc98eb7?auto=format&fit=crop&w=600', 'lake'),
('Vehicle Hire (4x4)', 'Strong Land Cruisers with pop-up roofs for game viewing.', 'From $70 / day', 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=600', 'safari'),
('Bird Watching', 'Spot over 200 species of birds with our expert ornithologists.', 'From $30 / person', 'https://images.unsplash.com/photo-1452570053594-1b985d6ea890?auto=format&fit=crop&w=600', 'hiking');
