-- 1. BOOKINGS TABLE
create table public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  activity text not null,
  travel_date date not null,
  guests text not null,
  name text,        -- Added name
  email text,       -- Added email
  status text default 'new' -- new, contacted, booked
);

-- Enable Security
alter table public.bookings enable row level security;

-- Policy 1: Everyone can insert (submit form)
create policy "Public can insert bookings"
on public.bookings for insert
with check (true);

-- Policy 2: Only Admin can view (authenticated users)
create policy "Admins can view bookings"
on public.bookings for select
using (auth.role() = 'authenticated');

-- 2. TESTIMONIALS TABLE
create table public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  content text not null,
  rating int default 5,
  approved boolean default false -- Needs admin approval to show
);

-- Enable Security
alter table public.testimonials enable row level security;

-- Policy 1: Everyone can insert (submit review)
create policy "Public can submit reviews"
on public.testimonials for insert
with check (true);

-- Policy 2: Public can view APPROVED reviews
create policy "Public can view approved reviews"
on public.testimonials for select
using (approved = true);

-- Policy 3: Admins can view ALL reviews
create policy "Admins can view all reviews"
on public.testimonials for select
using (auth.role() = 'authenticated');

-- Policy 4: Admins can update via dashboard (approve)
create policy "Admins can update reviews"
on public.testimonials for update
using (auth.role() = 'authenticated');

-- Policy 5: Admins can delete
create policy "Admins can delete reviews"
on public.testimonials for delete
using (auth.role() = 'authenticated');
